<?php

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 * Implements hook_help
 */

function drupal_hello_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'drupal.hello':
            $output = '';
            $output .= "<p>" . t('This hook work') . "</p>";
            return $output;
    }
  }